replicaCount: 1

image:
  repository: mlops-registry:5000/mlops-mini-lab-serve
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: traefik
  host: serve.mlops.local
  path: /

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  MODEL_URI: "file:./models/model.joblib"
  N_FEATURES: "8"
  WEB_CONCURRENCY: "2"

livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 10
  periodSeconds: 15

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 5
  periodSeconds: 10
